### PR TITLE
Initial commit

### PR DESCRIPTION
**Pull request by J-Puls**
I have included comments within the code to further explain what I have done. Hope this helps!

-Added mobile control implementation (touch-friendly buttons with custom SVG icons)
-Rearranged file structure (grouped similar files in their own directories)
-Some cleanup done to keyboard control logic

### CODE REVIEW

**Comment by markcornwell** [comment]
Nice work.  Both functional and tasteful.  I had added a star with gravity a few commits back, so had to deconflict a few nits to push the merge through, but was straightforward.

**Comment by markcornwell** [comment]
Was testing this out on my iPhone.  Icons on buttons look great.  But, the ships are not displaying on the screen.  First time running on the iPhone.  Wondering if the screen geometry is different.  I do see missles go by when I fire, but no ships.  I do get the flickering star I added, but not fully centered on the screen.  It looks a bit low.  Suspect ships are off screen.  Will experiment with parm file and see what happens.

**Comment by J-Puls** [comment]
Hmm, strange, worked beautifully on Android and Chrome simulated devices. Unfortunately I don't have an iOS device so I can't do any real-time testing for that. I'll take a look when I have a chance and see if I can reproduce the issue outside of Safari

**Comment by J-Puls** [comment]
I took a look at the updated master with the star mechanics (nicely done, by the way) and was not able to reproduce the issue exactly as you described on any of my non-iOS devices. However, after the ships are destroyed by the star, I am still able to fire missiles from the "dead" ship (now inside the star), so perhaps this is where your phantom missiles are coming from.

**Pull request merged**
